name: Deploy to AWS Lambda

on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip Lambda function code only
        run: |
          zip -r lambda.zip campsite_finder

      - name: Deploy to Lambda
        uses: appleboy/lambda-action@v0.1.8
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION || 'us-east-2' }}
          function_name: campsite_finder
          zip_file: lambda.zip